version: '2'

services:
  openldap:
    container_name: ldap-server
    image: bitnami/openldap:2
    ports:
      - '389:1389'
      - '636:1636'
    environment:
      - LDAP_ROOT=dc=callcenter,dc=org
      - LDAP_ADD_SCHEMAS=yes
      - LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis
      - LDAP_ADMIN_USERNAME=${ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - LDAP_CUSTOM_LDIF_DIR=Customldifs/
      - BITNAMI_DEBUG=true
      # - LDAP_ALLOW_ANON_BINDING=no #uncomment this force login
    volumes:
      - './storage:/bitnami/openldap'
      - ./Customldifs:/Customldifs
