version: '2'

services:
  openldap:
    container_name: ldap-server
    image: bitnami/openldap:2
    ports:
      - '389:1389'
      - '636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=${ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=${USER_PASSWORDS}
    volumes:
      - './storage:/bitnami/openldap'