name: bbdgrad-ldap
version: '2'

services:
  openldap:
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=${ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=${USER1_PASSSWORD},${USER2_PASSWORD}
    volumes:
      - './containerFiles:/bitnami/openldap'
  myapp:
    image: 'bitnami/openldap'
volumes:
  openldap_data:
    driver: local
