version: '2'

networks:
  my-network:
    driver: bridge
services:
  openldap:
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=${ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    networks:
      - my-network
    volumes:
      - 'openldap_data:/bitnami/openldap'
  myapp:
    image: 'bitnami/openldap'
    networks:
      - my-network
volumes:
  openldap_data:
    driver: local
